version: '3'
services:
    beges:
        build: ./app
        environment:
            - GMAP_API_KEY=${GMAP_API_KEY}
            - APP_ADMIN_NAME=${APP_ADMIN_NAME}
            - APP_ADMIN_PWD=${APP_ADMIN_PWD}
            - APP_ADMIN_EMAIL=${APP_ADMIN_EMAIL}
        volumes:
            - ${DATA_DIR}:/data
